### ISSUE TITLE
`enif_inspect_iolist_as_binary` cannot decode a valid term

### ISSUE THREAD

**Issue by zv** [tokenrove/niffy#7]
first up, i'm here to award you the "man with da plan" genius grant for this project. this long venerated prize confers substantial benefits, up to and including lots of props and worldwide love no matter where you go.

unfortunately I can't come with entirely good news, because when `iolist_to_binary` encounters a binary term, it borks no matter it's contents. I've tried
1. Manually crafting a binary through `enif_make_binary`
2. Aliasing `enif_inspect_iolist_as_binary` to `enif_inspect_as_binary` -- I'd no idea if this was a sensible idea and it's not.

I haven't done any significant debugging yet, but _MYYYY_ guess is that the parsing of the term is incorrect. I'm going to take a further look at it when I get some time.

> ==22361== Process terminating with default action of signal 6 (SIGABRT)
> ==22361==    at 0x506DA28: raise (in /usr/lib64/libc-2.22.so)
> ==22361==    by 0x506F629: abort (in /usr/lib64/libc-2.22.so)
> ==22361==    by 0x40562C: inner_iolist_to_binary (nif_stubs.c:374)
> ==22361==    by 0x405760: iolist_to_binary (nif_stubs.c:404)
> ==22361==    by 0x4066BB: enif_inspect_iolist_as_binary (nif_stubs.c:815)
> ==22361==    by 0x57FCA22: decode_ber_tlv_raw (asn1_erl_nif.c:1253)
> ==22361==    by 0x4038A6: call (niffy.c:84)
> ==22361==    by 0x404000: niffy_handle_statement (niffy.c:147)
> ==22361==    by 0x412D01: yy_reduce (parse.y:56)
> ==22361==    by 0x412D01: Parse (parse.c:1293)
> ==22361==    by 0x40320B: main (main.c:100)

**Comment by tokenrove** [comment]
Thanks for the bug report!  I figure there's still a fair few issues like this, where my own NIFs just haven't happened to touch some part of the (very stubby) nif stubs.  A quick gander suggests an immediate fix so I'll put in a test case and a fix today with any luck.

**Comment by zv** [comment]
Looks like this addressed the issue, but now I"m getting a bad argument -- Am I passing in the format correctly? Do I need to pass in erlang terms directly?

```
echo '[<<4,0>>]' | ./fuzz_skeleton $ERL_TOP/liib/asn1/priv/lib/x86_64-unknown-linux-gnu/asn1rt_nif.so jiffy_test.term 
raised exception badarg
badarg
```

`niffy` gives the same error.

**Comment by tokenrove** [comment]
Well, there are probably many more things to fix, but it should be noted that `fuzz_skeleton` feeds the input to your template file (`jiffy_test.term`) as a variable `Input` bound to a binary.  So in this case, whatever you've got in your template is getting `Input = <<"[<<4,0>>]">>.` first, which might not be what you are expecting.  (niffy's term parser is not invoked for stdin when fuzz_skeleton is used)

BTW, please feel free to open scads of issues: I know there are numerous parts of the enif API that need to be completed, and the documentation could be clarified, too.  I'll try to address things as quickly as possible.  Also, I'm planning to start fuzzing some other NIFs soon which will force me to fill out most of what's missing.

**Comment by zv** [comment]
EDIT: Manually passing an argument as an IOlist works, strangely enough, although the `fuzz_skeleton` seems to not work, even with modifying the input format.

I'm with you so far, here is my term file supplied to `fuzz_skeleton` (i.e the contents of `jiffy_term.term`)

```
_ = niffy:load_nif(asn1rt_nif, []).
asn1rt_nif:decode_ber_tlv_raw(Input).
```

consequently, a niffy invocation has the same error:

```
./niffy --lazy ~/z/zv-otp/lib/asn1/priv/lib/x86_64-unknown-linux-gnu/asn1rt_nif.so <<EOF
asn1rt_nif:decode_ber_tlv_raw(<<1,2,3>>).
EOF

```

`asn1rt_nif` does use a ton of enifs not widely used in other nifs -- I'm working on trying to debug this right now, if I can fix it I'll cast over a PR.

**Comment by tokenrove** [comment]
Ah, of course.  Getting wrapped up in the obvious bug fix, I totally failed to fix the actual issue -- right now niffy doesn't consider just a binary as an iolist.  Will reopen and fix tomorrow.

**Comment by zv** [comment]
You've done just fine -- I've been able to modify `fuzz_skeleton` to work just fine, but it somewhat confusing.
